# Generated by Django 2.2.4 on 2019-11-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='pcommission',
            field=models.CharField(default='any', max_length=50),
            preserve_default=False,
        ),
    ]
