# Generated by Django 2.2.4 on 2019-11-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, null=True, unique=True)),
                ('ccontact', models.IntegerField(null=True, unique=True)),
                ('cdescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=50)),
                ('pnr', models.CharField(max_length=50)),
                ('paymentdate', models.DateField()),
                ('installment', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
